### ISSUE TITLE
Add support for CentOS

### ISSUE THREAD

**Issue by reypm** [jtreminio/dashtainer#43]
It's any chance to add support for CentOS? I've seen all the Dockerfiles uses Debian. How hard that would be?

**Comment by jtreminio** [comment]
You can run these containers inside a CentOS server if you wish.

After 5+ years of PuPHPet initially supporting Ubuntu, Debian and CentOS then only Ubuntu and CentOS, I will not be supporting anything but Ubuntu in Dashtainer.
